### ISSUE TITLE
Implement custom code embedding/inclusion

### ISSUE THREAD

**Issue by expede** [Finhaven/EthereumStatusCodes#13]
Via @carchrae 

> the examples are great, but i wonder if there isn't a more elegant way to map a validator to the hex for app specific reasons, (eg, x05 in https://github.com/Finhaven/EthereumStatusCodes/blob/2679e92250462cad6a34af863d3ec66c732c203a/contracts/validators/FinancialValidator.sol#L7 ). like if there was a helper that mapped `FinancialValidator.reasons = customCodes([ 'insufficientFunds']) - or some other method to avoid pointing to magic strings. )

A user should be able to map names from a custom enum into the main code set

For example

```solidity
contract Phone {
    enum Call {
        Disconnected,
        Connected,
        CallStarted,
        OnHold
    }
}

customCode(Phone.Call.Disconnected) == hex"A0"
// true
```

**Comment by carchrae** [comment]
so, from `FinancialValidator` could you have 

```solidity
contract FinancialValidator
enum Reasons { 
   InsufficientFunds
 } 


.... 



if (_amount < 1000) { return customCode(FinancialValidator.Reasons.InsufficientFunds); }

```

**Comment by carchrae** [comment]
but i'm not sure.  it would be nicer to have 

```solidity
if (_amount < 1000) { return FinancialValidator.Reasons.InsufficientFunds; }
```

**Comment by carchrae** [comment]
or maybe just 
```solidity
contract FinancialValidator {
    byte InsufficientFunds =  hex"A0";
    function checkBalance(int _amount) internal pure returns (Status.Reason) {
        if (_amount < 1000) { 
           return InsufficientFunds; 
        }
        else { 
          return Status.Reason.Success; 
        }
    }
```

**Comment by carchrae** [comment]
my eyes are burning - i'm not sure my last example makes sense.  time to step away from the machine.  8)

**Comment by expede** [comment]
Hmm, yeah. It's a fair point. `byte InsufficientFunds =  hex"A0";` works 👍🏻 I don't think that it'll compile as `Status.Reason`. There's currently no way to go from an number to an enum in Solidity 😭 `byte` is a built-in type, so we can cast the `Status.Reason.Success` to `byte`.

I agree that if you have some custom codes, using the hex values directly makes sense. If someone wanted to restrict return values via a type, the enum is more restricted than `byte`.

I think that I see where the confusion is, and I'll add some notes to the code examples 😄
