### ISSUE TITLE
Throw/revert

### ISSUE THREAD

**Issue by naumenkogs** [Finhaven/EthereumStatusCodes#2]
Throwing an error kills all the events and currently there is no way to pass some data along with throw (WIP).

In _Token Validation_ diagram your first user flow has throw-revert. I think we should return a status instead. However, ERC20 assumes return bool for transfer function (see #3) — we should raise status events at least and not throw, but return false in case of failure.

**Comment by expede** [comment]
Hmm, yeah, for our specific use case you're right. In the diagram I wanted to show that this doesn't preclude throwing, and in fact you may very well want to. If you can think of a better example, I'd very much like to switch that diagram to it. It doesn't have to be validation, that was just what was top-of-mind when looking for ways to illustrate the mechanism.
