### ISSUE TITLE
Buy method

### ISSUE THREAD

**Issue by naumenkogs** [Finhaven/EthereumStatusCodes#3]
Both your diagrams have a buy call, going to the Token instance.

I think it is not super-clear. Should we use transfer() instead? In this case, returning type should be bool, as in ERC20

**Comment by expede** [comment]
> I think it is not super-clear. Should we use transfer() instead?

It's intentionally avoiding specific method names to stay abstract. This is a low-fidelity sketch to display a mechanism, not an actual concrete example. `buy()` could be ERC20, ERC777, ERC721, a DEX, and so on.
