### ISSUE TITLE
WebConf: Friday, April 20th, 9AM PST

### ISSUE THREAD

**Issue by bmann** [Finhaven/EthereumStatusCodes#6]
We'll be doing a live web conf using Zoom video to talk about EthereumStatusCodes, led by @expede. There will be an overview of the problem, solution, and Q&A.

### Time:
- 9AM PST, time converter here https://www.timeanddate.com/worldclock/converter.html?iso=20180420T160000&p1=256&p2=179&p3=37&p4=136&p5=170&p6=248&p7=237

### Location: 
- Zoom Video Meeting ID: 559 826 261
- Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/559826261
- Phone Canada: +1 647 558 0588 
- International numbers available: https://zoom.us/u/dPQsPli28

**Comment by expede** [comment]
Will schedule another shortly 😄
